import { Exercise } from "@/types";

export const exerciseData: Exercise[] = [
  {
    name: "Barbell Bench Press",
    id: "bb-bench-press",
    url: "https://www.youtube.com/watch?v=gRVjAtPip0Y",
    description:
      "Lie on a flat bench and press a barbell up from chest level to full arm extension",
    category: "strength",
    primaryMuscle: "chest",
    equipment: "barbell",
  },
  {
    name: "Back Squat",
    id: "back-squat",
    url: "https://www.youtube.com/watch?v=bEv6CCg2BC8",
    description:
      "Place a barbell on upper back, squat down until thighs are parallel to ground, then return to standing",
    category: "strength",
    primaryMuscle: "quadriceps",
    equipment: "barbell",
  },
  {
    name: "Deadlift",
    id: "deadlift",
    url: "https://www.youtube.com/watch?v=ytGaGIn3SjE",
    description:
      "Lift a barbell from the ground to hip level while maintaining a straight back",
    category: "strength",
    primaryMuscle: "back",
    equipment: "barbell",
  },
  {
    name: "Pull-up",
    id: "pull-up",
    url: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
    description:
      "Hang from a bar and pull yourself up until chin is over the bar",
    category: "bodyweight",
    primaryMuscle: "back",
    equipment: "pull-up bar",
  },
  {
    name: "Overhead Press",
    id: "overhead-press",
    url: "https://www.youtube.com/watch?v=2yjwXTZQDDI",
    description:
      "Press a barbell from shoulder level to overhead while standing",
    category: "strength",
    primaryMuscle: "shoulders",
    equipment: "barbell",
  },
  {
    name: "Dumbbell Row",
    id: "db-row",
    url: "https://www.youtube.com/watch?v=roCP6wCXPqo",
    description:
      "Bend over with one hand on bench, pull dumbbell to chest level",
    category: "strength",
    primaryMuscle: "back",
    equipment: "dumbbell",
  },
  {
    name: "Leg Press",
    id: "leg-press",
    url: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
    description:
      "Push weight away using legs while seated in leg press machine",
    category: "strength",
    primaryMuscle: "quadriceps",
    equipment: "machine",
  },
  {
    name: "Dumbbell Lunges",
    id: "db-lunges",
    url: "https://www.youtube.com/watch?v=D7KaRcUTQeE",
    description: "Step forward into lunge position while holding dumbbells",
    category: "strength",
    primaryMuscle: "quadriceps",
    equipment: "dumbbell",
  },
  {
    name: "Lat Pulldown",
    id: "lat-pulldown",
    url: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
    description: "Pull cable attachment down to chest while seated",
    category: "strength",
    primaryMuscle: "back",
    equipment: "cable machine",
  },
  {
    name: "Dumbbell Shoulder Press",
    id: "db-shoulder-press",
    url: "https://www.youtube.com/watch?v=qEwKCR5JCog",
    description: "Press dumbbells overhead while seated or standing",
    category: "strength",
    primaryMuscle: "shoulders",
    equipment: "dumbbell",
  },
  {
    name: "Bicep Curls",
    id: "bicep-curls",
    url: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
    description: "Curl dumbbells or barbell from hip level to shoulder level",
    category: "isolation",
    primaryMuscle: "biceps",
    equipment: "dumbbell",
  },
  {
    name: "Tricep Pushdown",
    id: "tricep-pushdown",
    url: "https://www.youtube.com/watch?v=2-LAMcpzODU",
    description: "Push cable attachment down using triceps while standing",
    category: "isolation",
    primaryMuscle: "triceps",
    equipment: "cable machine",
  },
  {
    name: "Leg Extensions",
    id: "leg-extensions",
    url: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
    description: "Extend legs from seated position using machine",
    category: "isolation",
    primaryMuscle: "quadriceps",
    equipment: "machine",
  },
  {
    name: "Calf Raises",
    id: "calf-raises",
    url: "https://www.youtube.com/watch?v=-M4-G8p8fmc",
    description: "Raise heels off ground while standing on elevated surface",
    category: "isolation",
    primaryMuscle: "calves",
    equipment: "bodyweight",
  },
  {
    name: "Dips",
    id: "dips",
    url: "https://www.youtube.com/watch?v=2z8JmcrW-As",
    description: "Lower body between parallel bars and push back up",
    category: "bodyweight",
    primaryMuscle: "chest",
    equipment: "parallel bars",
  },
  {
    name: "Russian Twists",
    id: "russian-twists",
    url: "https://www.youtube.com/watch?v=wkD8rjkodUI",
    description: "Seated with feet off ground, rotate torso side to side",
    category: "core",
    primaryMuscle: "abs",
    equipment: "bodyweight",
  },
  {
    name: "Plank",
    id: "plank",
    url: "https://www.youtube.com/watch?v=ASdvN_XEl_c",
    description: "Hold push-up position with forearms on ground",
    category: "core",
    primaryMuscle: "abs",
    equipment: "bodyweight",
  },
  {
    name: "Cable Crossover",
    id: "cable-crossover",
    url: "https://www.youtube.com/watch?v=taI4XduLpTk",
    description: "Pull cable handles together in front of chest",
    category: "isolation",
    primaryMuscle: "chest",
    equipment: "cable machine",
  },
  {
    name: "Face Pulls",
    id: "face-pulls",
    url: "https://www.youtube.com/watch?v=eIq5CB9JfKE",
    description: "Pull rope attachment to face level with high cable",
    category: "isolation",
    primaryMuscle: "shoulders",
    equipment: "cable machine",
  },
  {
    name: "Romanian Deadlift",
    id: "romanian-deadlift",
    url: "https://www.youtube.com/watch?v=5Isl_IL_o6Q",
    description: "Hinge at hips with slight knee bend while holding weight",
    category: "strength",
    primaryMuscle: "hamstrings",
    equipment: "barbell",
  },
  {
    name: "Hammer Curls",
    id: "hammer-curls",
    url: "https://www.youtube.com/watch?v=zC3nLlEvin4",
    description: "Curl dumbbells with palms facing each other",
    category: "isolation",
    primaryMuscle: "biceps",
    equipment: "dumbbell",
  },
  {
    name: "Incline Bench Press",
    id: "incline-bench-press",
    url: "https://www.youtube.com/watch?v=SrqOu55lrYU",
    description: "Press weight while lying on incline bench",
    category: "strength",
    primaryMuscle: "chest",
    equipment: "barbell",
  },
  {
    name: "Lateral Raises",
    id: "lateral-raises",
    url: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
    description: "Raise dumbbells to shoulder level with straight arms",
    category: "isolation",
    primaryMuscle: "shoulders",
    equipment: "dumbbell",
  },
  {
    name: "Hip Thrust",
    id: "hip-thrust",
    url: "https://www.youtube.com/watch?v=SEdqd1n0cvg",
    description: "Thrust hips upward while upper back rests on bench",
    category: "strength",
    primaryMuscle: "glutes",
    equipment: "barbell",
  },
  {
    name: "Push-ups",
    id: "push-ups",
    url: "https://www.youtube.com/watch?v=IODxDxX7oi4",
    description:
      "Lower body to ground and push back up while maintaining plank position",
    category: "bodyweight",
    primaryMuscle: "chest",
    equipment: "bodyweight",
  },
  {
    name: "Seated Cable Rows",
    id: "seated-cable-rows",
    url: "https://www.youtube.com/watch?v=GZbfZ033f74",
    description:
      "Pull cable attachment towards lower chest while seated with feet braced",
    category: "strength",
    primaryMuscle: "back",
    equipment: "cable machine",
  },
  {
    name: "Leg Curl",
    id: "leg-curl",
    url: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
    description:
      "Curl weight using hamstrings while lying face down on machine",
    category: "isolation",
    primaryMuscle: "hamstrings",
    equipment: "machine",
  },
  {
    name: "Chest Flyes",
    id: "chest-flyes",
    url: "https://www.youtube.com/watch?v=eozdVDA78K0",
    description:
      "Lower dumbbells out to sides while lying on bench, then bring together over chest",
    category: "isolation",
    primaryMuscle: "chest",
    equipment: "dumbbell",
  },
  {
    name: "T-Bar Row",
    id: "t-bar-row",
    url: "https://www.youtube.com/watch?v=j3Igk5nyZE4",
    description:
      "Row weight up while bent over using T-bar apparatus or barbell in corner",
    category: "strength",
    primaryMuscle: "back",
    equipment: "barbell",
  },
  {
    name: "Smith Machine Squat",
    id: "smith-squat",
    url: "https://www.youtube.com/watch?v=y1zCvyFZlE8",
    description: "Perform squat movement using Smith machine guided barbell",
    category: "strength",
    primaryMuscle: "quadriceps",
    equipment: "smith machine",
  },
  {
    name: "Preacher Curl",
    id: "preacher-curl",
    url: "https://www.youtube.com/watch?v=fIWP-FRFNU0",
    description: "Curl weight while arms rest on preacher bench pad",
    category: "isolation",
    primaryMuscle: "biceps",
    equipment: "barbell",
  },
  {
    name: "Reverse Flyes",
    id: "reverse-flyes",
    url: "https://www.youtube.com/watch?v=9R5f4oIjwq8",
    description:
      "Raise dumbbells out to sides while bent over to target rear deltoids",
    category: "isolation",
    primaryMuscle: "shoulders",
    equipment: "dumbbell",
  },
  {
    name: "Ab Crunch Machine",
    id: "crunch-machine",
    url: "https://www.youtube.com/watch?v=_O1xunCfYEM",
    description: "Crunch forward against resistance using dedicated ab machine",
    category: "isolation",
    primaryMuscle: "abs",
    equipment: "machine",
  },
  {
    name: "Standing Calf Raise Machine",
    id: "standing-calf-machine",
    url: "https://www.youtube.com/watch?v=YMmgqO8Jo-k",
    description:
      "Raise heels against resistance while standing on machine platform",
    category: "isolation",
    primaryMuscle: "calves",
    equipment: "machine",
  },
  {
    name: "Front Squat",
    id: "front-squat",
    url: "https://www.youtube.com/watch?v=v-mQm_droHg",
    description: "Perform squat with barbell racked across front deltoids",
    category: "strength",
    primaryMuscle: "quadriceps",
    equipment: "barbell",
  },
  {
    name: "Seated Leg Curl",
    id: "seated-leg-curl",
    url: "https://www.youtube.com/watch?v=ELOCsoDSmrg",
    description: "Curl weight using hamstrings while seated on machine",
    category: "isolation",
    primaryMuscle: "hamstrings",
    equipment: "machine",
  },
  {
    name: "Decline Bench Press",
    id: "decline-bench-press",
    url: "https://www.youtube.com/watch?v=LfyQBUKR8SE",
    description: "Press weight while lying on decline bench",
    category: "strength",
    primaryMuscle: "chest",
    equipment: "barbell",
  },
  {
    name: "Machine Chest Press",
    id: "machine-chest-press",
    url: "https://www.youtube.com/watch?v=xUm0BiZCWlQ",
    description: "Press weight forward using chest press machine",
    category: "strength",
    primaryMuscle: "chest",
    equipment: "machine",
  },
  {
    name: "Arnold Press",
    id: "arnold-press",
    url: "https://www.youtube.com/watch?v=3ml7BH7mNwQ",
    description:
      "Press dumbbells overhead while rotating from forward to lateral position",
    category: "compound",
    primaryMuscle: "shoulders",
    equipment: "dumbbell",
  },
  {
    name: "Close Grip Bench Press",
    id: "close-grip-bench",
    url: "https://www.youtube.com/watch?v=nEF0bv2FW94",
    description:
      "Perform bench press with hands shoulder-width apart to target triceps",
    category: "strength",
    primaryMuscle: "triceps",
    equipment: "barbell",
  },
  {
    name: "Pendlay Row",
    id: "pendlay-row",
    url: "https://www.youtube.com/watch?v=ZlRrIsoDpKg",
    description:
      "Row barbell from floor to chest while maintaining horizontal torso position",
    category: "strength",
    primaryMuscle: "back",
    equipment: "barbell",
  },
  {
    name: "Hack Squat",
    id: "hack-squat",
    url: "https://www.youtube.com/watch?v=0tn5K9NlCfo",
    description: "Perform squat movement on angled hack squat machine",
    category: "strength",
    primaryMuscle: "quadriceps",
    equipment: "machine",
  },
  {
    name: "Cable Lateral Raise",
    id: "cable-lateral-raise",
    url: "https://www.youtube.com/watch?v=PPrzBWZDOhA",
    description:
      "Raise cable outward to side while standing sideways to machine",
    category: "isolation",
    primaryMuscle: "shoulders",
    equipment: "cable machine",
  },
  {
    name: "Assisted Pull-up Machine",
    id: "assisted-pullup",
    url: "https://www.youtube.com/watch?v=y9i6B6oAHZY",
    description: "Perform pull-up with counterweight assistance from machine",
    category: "compound",
    primaryMuscle: "back",
    equipment: "machine",
  },
  {
    name: "Box Jumps",
    id: "box-jumps",
    url: "https://www.youtube.com/watch?v=52r_Ul5k03g",
    description: "Jump onto raised platform with both feet, step back down",
    category: "plyometric",
    primaryMuscle: "quadriceps",
    equipment: "box",
  },
  {
    name: "Dragon Flags",
    id: "dragon-flags",
    url: "https://www.youtube.com/watch?v=moyFIvRrS0s",
    description:
      "Lower and raise straight body while gripping bench behind head",
    category: "core",
    primaryMuscle: "abs",
    equipment: "bench",
  },
  {
    name: "Bulgarian Split Squat",
    id: "bulgarian-split-squat",
    url: "https://www.youtube.com/watch?v=2C-uNgKwPLE",
    description: "Perform single-leg squat with rear foot elevated on bench",
    category: "strength",
    primaryMuscle: "quadriceps",
    equipment: "dumbbell",
  },
  {
    name: "Cable Woodchoppers",
    id: "woodchoppers",
    url: "https://www.youtube.com/watch?v=pAplQXk3dkU",
    description: "Pull cable diagonally across body in chopping motion",
    category: "core",
    primaryMuscle: "abs",
    equipment: "cable machine",
  },
  {
    name: "Good Mornings",
    id: "good-mornings",
    url: "https://www.youtube.com/watch?v=YA-h3n9L4YU",
    description: "Bend forward at hips with barbell on upper back",
    category: "strength",
    primaryMuscle: "hamstrings",
    equipment: "barbell",
  },
  {
    name: "Hyperextensions",
    id: "hyperextensions",
    url: "https://www.youtube.com/watch?v=ph3pddpKzzw",
    description: "Raise torso up while lying face down on hyperextension bench",
    category: "isolation",
    primaryMuscle: "lower back",
    equipment: "bench",
  },
];
